# [Integer] Number of monte-carlo steps to simulate
monte-carlo-steps = 1000000

# [Integer] Number of equilibrium steps to simulate
equilibrium-steps = 0

# [Integer] Number of particles in the box volume
particle-count = 1024

# [ Float ] Fluid density in Lennard-Jones units
fluid-density = 0.6

# [ Float ] Temperature of the fluid
fluid-temperature = 0.9

# [ Float ] Maximum single-step displacement distance for the atoms
maximum-displacement = 0.2

# [ Float ] Cutoff radius for the Lennard-Jones potential
cutoff-distance = 2.5
